# Site settings
title: Chris Pietschmann
email: chris@build5nines.com
description: > # this means to ignore newlines until "baseurl:"
  I have more than 20 years of experience in the Software Development industry that includes working as a Consultant and Trainer in a wide array of different industries. Welcome to my resume and work history portfolio website!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pietschsoft.com" # the base hostname & protocol for your site
author: Chris Pietschmann
contact_url: https://build5nines.com/contact
twitter_username: build5nines # crpietschmann
twitter_username_2: build5nines
github_username:  crpietschmann
youtube_channel: build5nines
linkedin_url: http://linkedin.com/in/crpietschmann

# Build settings
include: ['_pages']
markdown: kramdown
permalink: /post/:year/:month/:day/:title
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap