# Site settings
title: Chris Pietschmann
email: chris@buildazure.com
description: > # this means to ignore newlines until "baseurl:"
  I have nearly 20 years of experience in the Software Development industry that includes working as a Consultant and Trainer in a wide array of different industries. Welcome to my resume and work history portfolio website!
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://chrispietschmann.com" # the base hostname & protocol for your site
twitter_username: crpietschmann
github_username:  crpietschmann
youtube_channel: buildazure

# Build settings
markdown: kramdown
permalink: /post/:year/:month/:day/:title:output_ext
plugins:
  - jekyll-redirect-from