# Site settings
title: Chris Pietschmann's website
email: chris@buildazure.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://chrispietschmann.com" # the base hostname & protocol for your site
twitter_username: crpietschmann
github_username:  crpietschmann

# Build settings
markdown: kramdown
permalink: /post/:year/:month/:day/:title:output_ext
plugins:
  - jekyll-redirect-from