name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
 
    - name: Sass Build - main.css
      uses: gha-utilities/sass-build@v0.2.5
      with:
        source: _site/css/main.scss
        destination: _sites/css/main.css
        
    - name: Sass Build - site.css
      uses: gha-utilities/sass-build@v0.2.5
      with:
        source: _site/css/site.scss
        destination: _sites/css/site.css

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: _site 
        # FOLDER: ${{ github.workspace }} # The folder the action should deploy.
