name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 0 * * 3 # Every Wednesday
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download Feed for Build5Nines
      run: |
        curl https://build5nines.com/wp-json/wp/v2/posts?author=2 --output ./latest_posts_build5nines.json
      working-directory: ${{ github.workspace }}/_data

    - name: Clean Feed for Build5Nines
      run: |
        #https://github.com/mdlincoln/jekyll-slack
        #https://www.cyberciti.biz/faq/how-to-use-sed-to-find-and-replace-text-in-files-in-linux-unix-shell/

        # remove unicode characters from JSON
        iconv -c -f utf-8 -t ascii latest_posts_build5nines.json >> latest_posts_build5nines.json # remove unicode characters

        sed -i 's/\\u[a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9]//g' latest_posts_build5nines.json
        sed -i 's/\\\//\//g' latest_posts_build5nines.json
        
        #cat latest_posts_build5nines.json
      working-directory: ${{ github.workspace }}/_data
        


    - name: Download Feed for Learn Build5Nines 
      run: |
        curl https://learn.build5nines.com/wp-json/ldlms/v1/sfwd-courses?per_page=10 --output ./learn_build5nines_courses.json
      working-directory: ${{ github.workspace }}/_data

    - name: Clean Feed for Learn Build5Nines
      run: |
        # remove unicode characters from JSON
        iconv -c -f utf-8 -t ascii learn_build5nines_courses.json >> learn_build5nines_courses.json # remove unicode characters

        sed -i 's/\\u[a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9]//g' learn_build5nines_courses.json
        sed -i 's/\\\//\//g' learn_build5nines_courses.json
        
        #cat learn_build5nines_courses.json
      working-directory: ${{ github.workspace }}/_data



    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
 
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: _site 
        # FOLDER: ${{ github.workspace }} # The folder the action should deploy.
